FROM maven:3.6.3-jdk-8 AS build
WORKDIR /usr/src/app
COPY . .
RUN mvn --batch-mode clean package

FROM openjdk:8-jdk-alpine
COPY --from=build /usr/src/app/target/petclinic-1.0.war app.war
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.war"]